### ISSUE TITLE
Improve LTR reset

### ISSUE THREAD

**Issue by worleydl** [o19s/hello-ltr#4]
Currently each lab resets the LTR store completely and works from scratch, this can get annoying when working with labs that build off the steps from previous ones.

Update reset_ltr so it only resets the models/feature stores associated with a given lab.

**Comment by DmitryKey** [comment]
in order to experiment with multiple feature and model stores, I have made some changes to reset mechanisms, that allow keeping existing feature stores / models. It might be a candidate for this issue.

The (trivial) changes were made to ltr.setup. Let me know, if this is something that will help achieve the original goal here.

**Comment by worleydl** [comment]
Thanks for the PR! I'm leaning towards having reset only reset particular featuresets and not the entire LTR store.  Then we can support a lesson resetting itself back to square one without nuking everything from the other lessons (as long as lessons make use of unique feature set names).  Do you have any thoughts about this approach?

**Comment by DmitryKey** [comment]
@worleydl yes, this approach makes sense to me. Only thing is that it might require some sort of declarative method, where we bind a set of feature stores / model names to a particular lesson.
The trick is, as you said, is to make sure we have unique feature stores / model names, but you could say that is solved by design of Solr (and I presume Elasticsearch): adding a feature with the same name to the same feature store is not possible.

What I'd do is to have some agreed upon prefix for models / feature stores:

    model-<unique-lesson-name>.json
    feature-store-<unique-lesson-name>.json

or, if we need multiple feature stores / models per lesson:

    model-1-<unique-lesson-name>.json
    feature-store-1-<unique-lesson-name>.json

If keep these in json files, we can:

1. version them
2. analyze and when removing a model, remove underlying feature store, by reading it from the "store" parameter.

What do you think?

**Comment by worleydl** [comment]
I like that idea a lot.  I may try to figure out a way of working with features stored as json files and inline.  Sometimes the inline editing in the notebook is nice for newcomers getting their feet wet but having separate files definitely makes sense especially for larger and more complicated featuresets.

**Comment by DmitryKey** [comment]
@worleydl agree on your point about inline editing -- offering some data structure on top of that could optimize for both use cases: inline vs being able to programmatically refresh only this lesson's configs and models. Something like:

    feature_store-1-<unique-lesson-name> = [
    #1
    {
      "name" : "title_has_phrase",
      "store": "title",
      "class" : "org.apache.solr.ltr.feature.SolrFeature",
      "params" : {
        "q" : "Title:\"${keywords})\"^=1"
      }
    },
    ]
    lesson_ltr_config = { feature_stores: [feature_store-1-<unique-lesson-name>]}

    # implement utils to serialize / deserialize the configs and utils 
    # for refreshing only this lesson's configs utilizing the lesson_ltr_config with standard keys.

also, having feature store / models in version control offers a path to productization.
